/* Skeleton Copyright (C) 2015, 2020 Paul N. Hilfinger and the Regents of the
 * University of California.  All rights reserved. */
package loa;

import ucb.gui2.TopLevel;
import ucb.gui2.LayoutSpec;

import java.awt.Dimension;
import javax.swing.JScrollPane;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import java.io.InputStream;
import java.io.IOException;
import java.io.StringWriter;

import java.util.concurrent.ArrayBlockingQueue;


/** The GUI controller for a LOA board and buttons.
 *  @author Dhruv Sirohi
 */
class GUI extends TopLevel implements View, Reporter {

    /** Minimum size of board in pixels. */
    private static final int MIN_SIZE = 500;

    /** Size of pane used to contain help text. */
    static final Dimension TEXT_BOX_SIZE = new Dimension(500, 700);

    /** Resource name of "About" message. */
    static final String ABOUT_TEXT = "loa/About.html";

    /** Resource name of Loa help text. */
    static final String HELP_TEXT = "loa/Help.html";

    /** A new window with given TITLE providing a view of a Loa board.
     * You EDIT here.*/
    GUI(String title) {
        super(title, true);
        addMenuButton("Game->New", this::newGame);
        addMenuButton("Game->Quit", this::quit);
        addMenuCheckBox("Settings->Auto->Black", false, this::black);
        addMenuCheckBox("Settings->Auto->White", true, this::white);
        addMenuCheckBox("Settings->Manual->Black", true, this::manBlack);
        addMenuCheckBox("Settings->Manual->White", false, this::manWhite);
        addMenuButton("Move->Undo", this::move);
        addMenuButton("Help->Details", this::help);
        _widget = new BoardWidget(_pendingCommands);
        add(_widget,
            new LayoutSpec("y", 2,
                           "height", 1,
                           "width", 3));
        addLabel("Next Move: White", "CurrentTurn",
                 new LayoutSpec("x", -2, "y", 0,
                                "height", 1,
                                "width", 3));
        addLabel("Moves made:", "Move number",
                new LayoutSpec("x", 2, "y", 1,
                        "height", 1,
                        "width", 3));
    }

    /** You made this. Undoes move. */
    private void move(String dummy) {
        _pendingCommands.offer("undo");
    }

    /** Response to "Quit" button click. */
    private void quit(String dummy) {
        _pendingCommands.offer("quit");
    }

    /** Makes black player manual. */
    private void manBlack(String dummy) {
        select("Settings->Auto->Black", false);
        _pendingCommands.offer("Manual black");
    }

    /** Makes white player manual. */
    private void manWhite(String dummy) {
        select("Settings->Auto->White", false);
        _pendingCommands.offer("Manual white");
    }

    /** Makes black player auto (Machine player). */
    private void black(String dummy) {
        select("Settings->Manual->Black", false);
        _pendingCommands.offer("auto black");
    }

    /** Makes white player auto (Machine player). */
    private void white(String dummy) {
        select("Settings->Manual->White", false);
        _pendingCommands.offer("auto white");
    }

    /** Response to "New Game" button click. */
    private void newGame(String dummy) {
        _pendingCommands.offer("new");
    }

    /** Response to help button press. */
    private void help(String dummy) {
        displayText("Help", HELP_TEXT);
    }
    /** Return the next command from our widget, waiting for it as necessary.
     *  The BoardWidget uses _pendingCommands to queue up moves that it
     *  receives.  This class uses _pendingCommands to queue up commands that
     *  are generated by clicking on menu items. */
    String readCommand() {
        try {
            _widget.setMoveCollection(true);
            String cmnd = _pendingCommands.take();
            _widget.setMoveCollection(false);
            return cmnd;
        } catch (InterruptedException excp) {
            throw new Error("unexpected interrupt");
        }
    }

    @Override
    public void update(Game controller) {
        Board board = controller.getBoard();

        _widget.update(board);
        if (board.winner() != null) {
            setLabel("CurrentTurn",
                     String.format("Winner: %s",
                                   board.winner().fullName()));
        } else {
            setLabel("CurrentTurn",
                     String.format("Next move: %s", board.turn().fullName()));
            setLabel("Move number",
                    String.format("Moves made: %d", board.movesMade() / 2));
        }

        boolean manualWhite = controller.manualWhite(),
            manualBlack = controller.manualBlack();

    }

    /** Display text in resource named TEXTRESOURCE in a new window titled
     *  TITLE. YOu MIGHT need to FIX update above as well.
     * Implementation note: It would have been more convenient to avoid
     * having to read the resource and simply use dispPane.setPage on the
     * resource's URL.  However, we wanted to use this application with
     * a nonstandard ClassLoader, and arranging for straight Java to
     * understand non-standard URLS that access such a ClassLoader turns
     * out to be a bit more trouble than it's worth. */
    private void displayText(String title, String textResource) {
        JFrame frame = new JFrame(title);
        JEditorPane dispPane = new JEditorPane();
        dispPane.setEditable(false);
        dispPane.setContentType("text/html");
        InputStream resource =
            GUI.class.getClassLoader().getResourceAsStream(textResource);
        StringWriter text = new StringWriter();
        try {
            while (true) {
                int c = resource.read();
                if (c < 0) {
                    dispPane.setText(text.toString());
                    break;
                }
                text.write(c);
            }
        } catch (IOException e) {
            return;
        }
        JScrollPane scroller = new JScrollPane(dispPane);
        scroller.setVerticalScrollBarPolicy(scroller.VERTICAL_SCROLLBAR_ALWAYS);
        scroller.setPreferredSize(TEXT_BOX_SIZE);
        frame.add(scroller);
        frame.pack();
        frame.setVisible(true);
    }

    @Override
    public void reportError(String fmt, Object... args) {
        showMessage(String.format(fmt, args), "Loa Error", "error");
    }

    @Override
    public void reportNote(String fmt, Object... args) {
        showMessage(String.format(fmt, args), "Loa Message", "information");
    }

    @Override
    public void reportMove(Move unused) {
    }

    /** The board widget. */
    private BoardWidget _widget;

    /** Queue of pending commands resulting from menu clicks and moves on the
     *  board.  We use a blocking queue because the responses to clicks
     *  on the board and on menus happen in parallel to the methods that
     *  call readCommand, which therefore needs to wait for clicks to happen. */
    private ArrayBlockingQueue<String> _pendingCommands =
        new ArrayBlockingQueue<>(5);

}
